### ISSUE TITLE
Change highlight colors

### ISSUE THREAD

**Issue by mtman** [FlashSystems/LogView#3]
Thanks for the great extension! I wonder if there is/can be a way to select the colors. 

None of my schemes (eg twilight) display errors in visible red:

![sublime_text_2017-09-06_11-34-50](https://user-images.githubusercontent.com/15874394/30104985-8b22c744-92f7-11e7-904b-c81decaf570c.png)
![sublime_text_2017-09-06_11-34-08](https://user-images.githubusercontent.com/15874394/30104979-86c9d6f6-92f7-11e7-84ec-d20b3209ef5a.png)

**Comment by FlashSystems** [comment]
The color can be changed indirectly. Select "Preferences" -> "Package Settings" -> "LogView" -> "Settings". There is a scope-setting for each type (error_scope, warning_scope, mark_scope). Just specify a scope name that gives you the color you wish with your theme.
