### ISSUE TITLE
underline whitespace?

### ISSUE THREAD

**Issue by tablatronix** [FlashSystems/LogView#4]
Was wondering why words are underlined and not the entire line, is this a scope thing or a sublime thing, or a theme thing

**Comment by FlashSystems** [comment]
This seems to be a sublime thing. The plugin marks the line independently from the theme and assigns a style. This style can be configured using the `highlight_style` option. If you use `fill` or `outline` the whole line (including spaces) is highlighted. Only if the style is `underline` the spaces are not underlined. I don't know why sublime is doing it that way and I don't think I have any way to change that.

**Comment by tablatronix** [comment]
I found a bunch of old known issues and bugs, i guess there is some limitation they could not fix.
